blog/urls.py
#coding:utf8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    url(r'regist/$',  'blog.views.regist_user'),	#注册
    url(r'login/$',  'blog.views.login_user'),	#登录
    url(r'index/$', 'blog.views.index'),		#主页
    url(r'logout/$' , 'blog.views.logout_user'),	#注销
    url(r'add/$', 'blog.views.post_add'),		#发帖子
    url(r'(\d+)/$' ,'blog.views.post_disp'),		#显示帖子
    url(r'(\d+)/reply/', 'blog.views.reply'),	#回帖
)

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
)

blog/models.py
#coding:utf8
from django.db import models
from django.contrib.auth.models import User

#发帖子
#新建模型后需要用 schemamigration  初始化一下blog应用
#python manage.py schemamigration blog --initial

#发帖
class Post(models.Model):
	title = models.CharField(max_length=50,verbose_name=u'标题')
	content = models.TextField(verbose_name=u'内容')
	p_date = models.DateTimeField(auto_now=True, auto_now_add=True)
	user = models.ForeignKey(User)

	def __unicode__(self):
		return self.title[:10]

#回帖
#添加模型后需要执行
# python manage.py schemamigration blog --auto	#修改数据库
# python manage.py migrate blog	#同步数据库
class  Reply(models.Model):
	content = models.TextField(verbose_name=u'内容')
	p_date = models.DateTimeField(auto_now=True, auto_now_add=True)
	post = models.ForeignKey(Post)
	user = models.ForeignKey(User)

blog/forms.py
#coding:utf8
from django import forms
from django.contrib.auth.models import User		#用户表
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate	#用户验证
from blog.models import Post ,Reply	#Post表(模型）

#用户注册
class UserRegistForm(forms.Form):
	username = forms.CharField(label=u'姓名')
	email = forms.EmailField(label=u'邮箱')
	password = forms.CharField(label=u'密码',widget=forms.PasswordInput())
	repassword = forms.CharField(label=u'确认密码',widget=forms.PasswordInput())
	
	def clean_username(self):
		username = self.cleaned_data.get('username')
		users = User.objects.filter(username = username)
		if len(users) > 0:
			raise forms.ValidationError(u'用户名已存在')
		return username
	
	def clean_email(self):
		email = self.cleaned_data.get('email')
		emails = User.objects.filter(email = email)
		if len(emails) > 0:
			raise forms.ValidationError(u'邮箱被占用')
		return emails
		
 	def clean(self):
 		password = self.cleaned_data.get('password')
 		repassword = self.cleaned_data.get('repassword')
 		if password != repassword:
 			raise forms.ValidationError(u'口令不一致')
 		else:
 			return self.cleaned_data
  #用户登录			
class UserLoginForm(forms.Form):
	username = forms.CharField(label=u'姓名')	
	password = forms.CharField(label=u'密码',widget=forms.PasswordInput())
	
	def clean_username(self):
		username = self.cleaned_data.get('username')
		users = User.objects.filter(username = username)	#筛选是“X”的用户，有是1，无是0
		if len(users) != 1:
			raise forms.ValidationError(u'用户不存在')
		return username	
	
	def clean(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		
		user = authenticate(username=username,password=password)
		if user is None:
			raise forms.ValidationError(u'用户/密码不正确')
		return self.cleaned_data

#发帖
class Post_addForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title','content']

#回帖
class ReplyForm(forms.ModelForm):
	class Meta:
		model = Reply
		field = ['content']

		
	
	
	

blog/views.py
#coding:utf8
from django.shortcuts import render, redirect	#导入redirect 重定向
from django.http import HttpResponse
from blog.forms import UserRegistForm, UserLoginForm, Post_addForm, ReplyForm	#导入form.py里的UserRegistForm对象
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User	#连接数据库
from blog.models import Post,Reply
#装饰器，发帖/回帖 判断用户是不是已经登录@login_required
from django.contrib.auth.decorators import login_required	

#用户注册
def regist_user(req):
	if req.method == "POST":
		urf = UserRegistForm(req.POST)
		if urf.is_valid():
		
			#print urf.cleaned_data
			username = urf.cleaned_data.get('username')
			email = urf.cleaned_data.get('email')
			password = urf.cleaned_data.get('password')
			#插入数据库
			User.objects.create_user(username=username, 
				password=password ,email=email)
			
			#return HttpResponse('regist ok!')
			return redirect('/user_login/')
	else:
		urf = UserRegistForm()
	return render(req,'regist.html',{'urf':urf})
	
#用户登录	
def login_user(req):
	if req.method == 'POST':
		urf = UserLoginForm(req.POST)
		if urf.is_valid():
			username = urf.cleaned_data.get('username')
			password = urf.cleaned_data.get('password')
			user = authenticate(username=username,password=password)
			login(req,user)
			#return HttpResponse('login ok ')
			return redirect('/blog/index/')

	else:
		urf = UserLoginForm()
		
	return render(req,'user_login.html', {'urf':urf})

#首页
def index(req):
	posts = Post.objects.all()
	return render(req, 'index.html',{'posts':posts})

#注销	
def logout_user(req):
	logout(req)
	return redirect('/blog/index/')

#发帖前执行登录检查
@login_required(login_url='/blog/login/')
#发帖
def post_add(req):
	if req.method == 'POST':
		urf = Post_addForm(req.POST)
		if urf.is_valid():
			urf = urf.save(commit = False)
			urf.user = req.user
			urf.save()
			return redirect('/blog/index')
	else:
		urf = Post_addForm()
	return render(req,'post_add.html',{'urf':urf})

#显示帖子
def post_disp(req,post_id):
	post = Post.objects.get(id=post_id)
	return render(req,'post_disp.html', {'post':post})

#回帖
#回帖前执行登录检查
@login_required(login_url='/blog/login/')
def reply(req,post_id):
	post = Post.objects.get(id=post_id)
	if req.method == "POST":
		urf = ReplyForm(req.POST)
		if urf.is_valid():
			urf = urf.save(commit=False)
			print req.user
			urf.user = req.user
			urf.post = post
			urf.save()
			return redirect('/blog/%s/' % post.id)
	else:
		urf = ReplyForm()
	return render(req, 'reply.html',{'urf':urf})

blog/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>User Index!</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap -->
	<link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet" media="screen"></head>
<body>
	<div class="container">
		<h1>index page</h1>
		<div>
			{% csrf_token %}
		{% if user.is_authenticated %}
			<p>Welcome, {{ user.username }}. Thanks for logging in.</p>
			<a href='/blog/logout/'>注销</a>
			{% else %}
			<p>
				Welcom,new user.Please
				<a href='/blog/login/'>login</a>
				|
				<a href='/blog/regist/'>注册</a>
				.
			</p>
			{% endif %}
		</div>
		<div>
			{%for post in posts%}
			<div>
				<h4> <a href="/blog/{{post.id}}">{{post.title}}</a></h4>
			</div>
			{%endfor%}
		</div>

	</div>

</body>
</html>

blog/templates/post_add.html
<h3>发帖</h3>
<form method="post">
{% csrf_token %}
<table>
{{ urf }}
<tr><td><input type="submit" value="发帖" /></td></tr>
</table>
</form>

blog/templates/post_disp.html
<h3>{{post.title}}</h3>
<p>{{post.content}}</p>
<div>
	{% for reply in post.reply_set.all %}
	<li>{{reply.content}}</li>
	{% endfor%}

</div>
<div><a href="/blog/{{post.id}}/reply/">回帖</a></div>

blog/templates/regist.html
<!DOCTYPE html>
<html>
<head>
	<title>User Regist!</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap -->
	<link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet" media="screen"></head>
<body>

	<div class="container">
		<h3>用户注册</h3>
		<form method='post'>{% csrf_token %}
			<table>
				{{ urf.as_table}}
				<tr>
					<td>
						<input type="submit" value="用户注册" class="btn" id="sbm" />
					</td>
				</tr>
			</table
		</form>
		</div>
		<script src="http://code.jquery.com/jquery.js"></script>
		<script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
		<script>
		function valid_username(){
			var username = $("#id_username").val();
			if(username.length < 4 ){
				return false;
			}else{
				return true;
			}
		}
		
		function valid_email(){
			var email = $("#id_email").val();
			var pattern = new RegExp(/^\w+@\w+\.\w+$/);
			return pattern.test(email);
		}
		
		function valid_password(){
			var password = $("#id_password").val();
			var repassword = $("#id_repassword").val();
			if(password.length < 6 ){
				return false;
			}
			if(password == repassword){
				return true;
			}else{
				return false;
			}
		}
		
		$(document).ready(function(){
			$("#sbm").click(function(event){
				var is_submit = true;
				
				if(!valid_username()){
					is_submit = false;
					alert("长度不能少于4位")
				}
				
				if(!valid_email()){
					is_submit = false;
					alert("邮箱地址有误")
				}
				
				if(!valid_password()){
					is_submit = false;
					alert("口令长度不能少于6位或两次输入密码不同")
				}
								
				if(!is_submit){
					event.preventDefault();
				}
				
			})
		});
		</script>
</body>
	</html>

blog/templates/reply.html
<h3>回帖</h3>
<form method="post">
{% csrf_token %}
<table>
{{ urf }}
<tr><td><input type="submit" value="回帖" /></td></tr>
</table>
</form>

blog/templates/user_login.html
<!DOCTYPE html>
<html>
<head>
	<title>User Login !</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap -->
	<link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet" media="screen"></head>
<body>

	<div class="container">
		<h3>登录</h3>
		<form method='post'>{% csrf_token %}
			<table>
				{{ urf.as_table}}
				<tr>
					<td>
						<input type="submit" value="用户登录" class="btn" id="sbm" />
					</td>
				</tr>
			</table
		</form>
		</div>
		<script src="http://code.jquery.com/jquery.js"></script>
		<script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
		<script>
		function valid_username(){
			var username = $("#id_username").val();
			if(username.length < 4 ){
				return false;
			}else{
				return true;
			}
		}
		/*
		function valid_email(){
			var email = $("#id_email").val();
			var pattern = new RegExp(/^\w+@\w+\.\w+$/);
			return pattern.test(email);
		}
		
		function valid_password(){
			var password = $("#id_password").val();
			var repassword = $("#id_repassword").val();
			if(password.length < 6 ){
				return false;
			}
			if(password == repassword){
				return true;
			}else{
				return false;
			}
		}
		*/
		$(document).ready(function(){
			$("#sbm").click(function(event){
				var is_submit = true;
				
				if(!valid_username()){
					is_submit = false;
					alert("长度不能少于4位")
				}
				/*
				if(!valid_email()){
					is_submit = false;
					alert("邮箱地址有误")
				}
				
				if(!valid_password()){
					is_submit = false;
					alert("口令长度不能少于6位或两次输入密码不同")
				}
				*/				
				if(!is_submit){
					event.preventDefault();
				}
				
			})
		});
		</script>
</body>
	</html>